# Generated by Django 4.1.4 on 2023-05-09 09:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_org_client_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='key',
            field=models.SlugField(default=api.models.org_default),
        ),
    ]
