# Generated by Django 4.1.4 on 2023-05-11 10:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_org_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='key',
            field=models.SlugField(default=api.models.sensor_default),
        ),
        migrations.AddField(
            model_name='usecase',
            name='key',
            field=models.SlugField(default=api.models.usecase_default),
        ),
        migrations.AlterField(
            model_name='org',
            name='domain',
            field=models.CharField(choices=[('Manufacturing - Automotive', 'Manufacturing - Automotive'), ('Manufacturing - Electronics', 'Manufacturing - Electronics'), ('Manufacturing - Aerospace', 'Manufacturing - Aerospace'), ('Manufacturing - Chemicals', 'Manufacturing - Chemicals'), ('Manufacturing - Food & Beverage', 'Manufacturing - Food & Beverage'), ('Manufacturing - Machinery', 'Manufacturing - Machinery'), ('Manufacturing - Metals', 'Manufacturing - Metals'), ('Manufacturing - Plastics', 'Manufacturing - Plastics'), ('Manufacturing - Textiles', 'Manufacturing - Textiles'), ('Healthcare - Hospitals', 'Healthcare - Hospitals'), ('Healthcare - Pharmaceuticals', 'Healthcare - Pharmaceuticals'), ('Transportation - Aviation', 'Transportation - Aviation'), ('Transportation - Rail', 'Transportation - Rail'), ('Energy - Oil & Gas', 'Energy - Oil & Gas'), ('Energy - Power Generation', 'Energy - Power Generation'), ('Utilities - Water Treatment', 'Utilities - Water Treatment'), ('Utilities - Waste Management', 'Utilities - Waste Management'), ('Mining - Metals', 'Mining - Metals'), ('Mining - Minerals', 'Mining - Minerals'), ('Construction - Building', 'Construction - Building'), ('Construction - Infrastructure', 'Construction - Infrastructure'), ('Agriculture - Farming', 'Agriculture - Farming'), ('Agriculture - Livestock', 'Agriculture - Livestock'), ('Retail - Supermarkets', 'Retail - Supermarkets'), ('Retail - Department Stores', 'Retail - Department Stores'), ('Hospitality - Hotels', 'Hospitality - Hotels'), ('Hospitality - Restaurants', 'Hospitality - Restaurants'), ('Education - Schools', 'Education - Schools'), ('Education - Universities', 'Education - Universities'), ('Government - Military', 'Government - Military'), ('Government - Municipalities', 'Government - Municipalities'), ('Technology - Software', 'Technology - Software'), ('Technology - Hardware', 'Technology - Hardware'), ('Finance - Banking', 'Finance - Banking'), ('Finance - Insurance', 'Finance - Insurance'), ('Media - Broadcasting', 'Media - Broadcasting'), ('Media - Publishing', 'Media - Publishing'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='org',
            name='industry',
            field=models.CharField(choices=[('Manufacturing', 'Manufacturing'), ('Oil and gas', 'Oil and gas'), ('Aerospace and defense', 'Aerospace and defense'), ('Automotive', 'Automotive'), ('Chemicals', 'Chemicals'), ('Energy and utilities', 'Energy and utilities'), ('Healthcare', 'Healthcare'), ('Mining', 'Mining'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Food and beverage', 'Food and beverage'), ('Transportation and logistics', 'Transportation and logistics'), ('Agriculture', 'Agriculture'), ('Construction', 'Construction'), ('Telecommunications', 'Telecommunications'), ('Banking and finance', 'Banking\xa0and\xa0finance')], max_length=50),
        ),
    ]
