# Generated by Django 4.1.4 on 2023-05-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sensor_key_usecase_key_alter_org_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='cat',
            field=models.CharField(choices=[('Temperature', 'Temperature'), ('Humidity', 'Humidity'), ('Light', 'Light'), ('Pressure', 'Pressure'), ('Sound', 'Sound'), ('Motion', 'Motion'), ('Proximity', 'Proximity'), ('Gas', 'Gas'), ('Color', 'Color'), ('Electricity', 'Electricity'), ('Magnetic', 'Magnetic'), ('Acceleration', 'Acceleration'), ('Gyroscope', 'Gyroscope'), ('Barometer', 'Barometer'), ('Infrared', 'Infrared'), ('UV', 'UV'), ('GPS', 'GPS'), ('Flow', 'Flow'), ('pH', 'pH'), ('Humectant', 'Humectant'), ('Smoke', 'Smoke'), ('CO2', 'CO2'), ('CO', 'CO'), ('Ozone', 'Ozone'), ('Water', 'Water'), ('Vibration', 'Vibration'), ('Weight', 'Weight'), ('Level', 'Level'), ('Radiation', 'Radiation'), ('Other', 'Other')], max_length=50),
        ),
    ]
